# Final Submission AI Fluency Competition

#### Code will take ~20 minutes to execute

#### importing relavant libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error
from tensorflow import keras
from keras.layers import Activation, Dense, Dropout, LSTM
from keras.models import Sequential
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.layers import LSTM
from sklearn.model_selection import train_test_split

#### please paste the training and testing set link from your system to properly execute the code

In [2]:
Training_link = r"C:\Users\sagprasad\Desktop\AI Forum data\AI Fluency - Competition Dataset\AI Fluency - Training Data.csv"
Testing_link = r"C:\Users\sagprasad\Desktop\AI Forum data\AI Fluency - Competition Dataset\AI Fluency - Testing Data.csv"

#### taking only relvant fields to fetch training data

In [3]:
fields = ['Asset_ID','Count','Open','High','Low','Close','Volume','VWAP']
data = pd.read_csv(Training_link,usecols = fields)

#### scaling the data into (0,1) range

In [4]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(data)
scaled_data

array([[0.00000000e+00, 2.36426231e-03, 5.70667051e-01, ...,
        5.71244877e-01, 4.15265969e-08, 5.70087235e-01],
       [6.25000000e-01, 1.78356630e-03, 3.04530806e-02, ...,
        3.04593958e-02, 4.42231605e-07, 3.04621628e-02],
       [1.00000000e+00, 1.72134887e-03, 9.29424984e-03, ...,
        9.28850985e-03, 5.42143742e-07, 9.28482239e-03],
       ...,
       [3.75000000e-01, 1.39470737e-02, 1.58653479e-05, ...,
        1.58374137e-05, 4.03590131e-03, 1.58438051e-05],
       [3.75000000e-01, 1.65809449e-02, 1.58344638e-05, ...,
        1.58110378e-05, 4.39789945e-03, 1.58245413e-05],
       [3.75000000e-01, 1.04317890e-02, 1.58080173e-05, ...,
        1.58189087e-05, 2.99152054e-03, 1.58088293e-05]])

In [5]:
x_train = np.array(scaled_data)
x_train

array([[0.00000000e+00, 2.36426231e-03, 5.70667051e-01, ...,
        5.71244877e-01, 4.15265969e-08, 5.70087235e-01],
       [6.25000000e-01, 1.78356630e-03, 3.04530806e-02, ...,
        3.04593958e-02, 4.42231605e-07, 3.04621628e-02],
       [1.00000000e+00, 1.72134887e-03, 9.29424984e-03, ...,
        9.28850985e-03, 5.42143742e-07, 9.28482239e-03],
       ...,
       [3.75000000e-01, 1.39470737e-02, 1.58653479e-05, ...,
        1.58374137e-05, 4.03590131e-03, 1.58438051e-05],
       [3.75000000e-01, 1.65809449e-02, 1.58344638e-05, ...,
        1.58110378e-05, 4.39789945e-03, 1.58245413e-05],
       [3.75000000e-01, 1.04317890e-02, 1.58080173e-05, ...,
        1.58189087e-05, 2.99152054e-03, 1.58088293e-05]])

#### defining LSTM model with 5 layers and 50 units having 0.5 dropout at each level

In [6]:
model = Sequential()
model.add(LSTM(units=50, return_sequences = True, input_shape=(x_train.shape[1],1)))
model.add(Dropout(0.5))
model.add(LSTM(units=50, return_sequences = True))
model.add(Dropout(0.5))
model.add(LSTM(units=50, return_sequences = True))
model.add(Dropout(0.5))
model.add(LSTM(units=50, return_sequences = True))
model.add(Dropout(0.5))
model.add(LSTM(units=50))
model.add(Dropout(0.5))
model.add(Dense(1))

#### Taking target field for model training

In [7]:
fields = ['Target']
data = pd.read_csv(Training_link,usecols = fields)
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(data)
y_train = np.array(scaled_data)
y_train

array([[0.41000945],
       [0.42690928],
       [0.41834679],
       ...,
       [0.4307308 ],
       [0.42978156],
       [0.42863044]])

In [8]:
np.set_printoptions(precision=17)

#### Training model 1 time(epoch =1 ) based on x_train and y_train with batch size of 4032

In [9]:
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(x_train,y_train,epochs=1,batch_size=4032)

1365/1365 [==============================] - 730s 527ms/step - loss: 0.0034


#### Taking test data based on relevant fields in output_data

In [10]:
fields = ['Asset_ID','Count','Open','High','Low','Close','Volume','VWAP']
output_data = pd.read_csv(Testing_link, usecols = fields)

In [11]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(output_data)
output_data = np.array(scaled_data)
output_data= np.reshape(output_data,(output_data.shape[0],output_data.shape[1],1))
output_data.shape

(1375849, 8, 1)

#### Predicting on output_data

In [12]:
output = model.predict(output_data)
output

42996/42996 [==============================] - 312s 7ms/step


array([[0.4312455 ],
       [0.43124843],
       [0.43124765],
       ...,
       [0.43097526],
       [0.4311539 ],
       [0.43126163]], dtype=float32)

In [13]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(data)

#### Inverse transforming the result

In [14]:
new_output = scaler.inverse_transform(output)
new_output

array([[-0.0022851995],
       [-0.0022835   ],
       [-0.0022839508],
       ...,
       [-0.0024424663],
       [-0.002338512 ],
       [-0.0022758169]], dtype=float32)

#### Converting result into pandas data frame

In [15]:
op = pd.DataFrame(new_output)
op

0
0       -0.002285
1       -0.002284
2       -0.002284
3       -0.002284
4       -0.002284
...           ...
1375844 -0.002276
1375845 -0.002088
1375846 -0.002442
1375847 -0.002339
1375848 -0.002276

[1375849 rows x 1 columns]

#### Creating csv file

In [16]:
op.to_csv('USI_AI Fluency Day_Team Alpha_vFinal.csv')

### Assumption :  Header are manually added into the result outcome after converting to CSV